FROM confluentinc/cp-kafka-connect-base:latest
COPY sinc-connector.json initialize-container.sh /

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hun-components"
RUN confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.7.0
