FROM ubuntu:latest

COPY sinc-connector.json initialize-container.sh /

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y kafkacat curl
# install mongosh
RUN curl https://downloads.mongodb.com/compass/mongodb-mongosh_1.0.0_amd64.deb -o mongosh.deb && \
    dpkg --install mongosh.deb

RUN bash /initialize-container.sh
# Modify command prompt
RUN echo 'PS1="\[\e[32m\][\e[mMongoDB Kafka Connector\e[32m]\e[m : "' >> ~/.bashrc

# Cleanup
RUN rm mongosh.deb
