name: Test workflow

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Install packages
        run: sudo apt-get install podman -y

      - name: Install podman-compose
        run: python3 -m pip install podman-compose
      
      - name: Deploy all containers
        run: podman-compose up -d --build
